server.port=8080
spring.application.name=scheduleTournament-api

# Firebase
firebase.database-url=https://elite-schedule-app-d0eb5-default-rtdb.europe-west1.firebasedatabase.app
firebase.service-account-path=classpath:serviceAccountKey.json
